services:
  db:
    image: postgres:14
    container_name: self-test-db
    environment:
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: passwordtest
      POSTGRES_DB: selftestdb
    ports:
      - "8000:8000"
    volumes:
      - selftest_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: self@admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    depends_on:
      - db
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  selftest_data:
    name: selftest_data